---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nop-dev
  labels:
    app: nopCommerce
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: nopcommerce
  template:
    metadata:
      name: nopcommerce
      labels:
        app: nopcommerce
    spec:
      containers:
        - name: nopcommerce
          image: nopcommerce
          args:
            - sleep
            - 10s
---
apiVersion:
kind:
metadata:
spec:


